<?php

include_once("db_meeting.php");
require_once("mmc_config.php");
require_once("hit_encryption.php");
require_once("platform_config.php");

$RELEATED_PATH = "../";
require_once($RELEATED_PATH . "fadmin.php");

// [jfish]修改中
// 修改一些基本設定跟function設定
// 已修改diskQuota.maxoutconnection.guaranteed三個變數的預設值
// 

Class JnjData
{

  // ID of the meeting's owner
  //   Owner ID defines where MCU will store the meeting data. Meeting data
  //   is stored in owner's directory, for example
  //   {recording-root-dir}/_user/{owner-id}/{meeting-id}
  var $ownerId;


  // create time
  var $timestamp;

  // Maximum disk usage for the owner (in MByte)
  //   Default is 50MB. Before MCU starts a new meeting, it checks the disk
  //   usage of meeting's owner. If the owner has exceed his/her quota, MCU
  //   will refuse to start a new meeting and it will send a warning message
  //   to the owner.  
  var $diskQuota;


  // Number of guests (outside connections) allowed
  //   Default is 10. People who are not connected from the "local range"
  //   are consider as guests. Local range is specified in the MCU license.
  //   Note: the actual maximum allowance is restricted by the MCU license
  //        and the current usage in MCU.
  var $maxoutconnection;

  // Name of the meeting's owner
  //   It will be displayed in JoinNet and recorded in meeting XML file
  var $ownerName;

  // Email address of the meeting's owner
  //   If there are any system messages, MCU will send them to this address
  var $ownerEmail;


  // ID of the meeting
  //   Usually, web application will generate a unique value for Meeting ID.
  //   Meeting ID is used by MCU to identify the meeting. Also, it is used
  //   to determine where MCU will store meeting data, for example
  //   {recording-root-dir}/_user/{owner-id}/{meeting-id}
  var $meetingId; // meeting id


  // The time JNJ file is created (UTC time in seconds)
  //   MCU uses this to check for the freshness of the request in JNJ file.
  //   The file is considered fresh if the time is within 5 minutes.
  //   Timestamp is not checked if "password" is present
  // var $timeStamp; // timeStamp

  // Title of the meeting
  //   This information is written to the recording XML file for information
  //   purpose only. It is not used by JoinNet nor MCU.
  var $meetingTitle;   // meeting tilte

  // Whether the meeting will be recorded
  //   Default is Yes. A recording JNR file will be generated by MCU if
  //   the meeting is recorded.
  //   0=No, 1=Yes(default)
  var $recording; // recording or not (1 is record )


  // Length of the meeting
  //   Default is 0. Maximum is 600.
  //   Note: When duration is equal to zero, the meeting will be considered
  //   person based. Otherwise, it will be considered event based.
  var $duration;

  // What instruction Joinnet should take upon receiving the JNJ file
  //   Choices are meeting, playback, download, delete, checkmessage
  //   For maximum compatibility, specify the command in all lowercase
  var $command;

  // Startup page to be shown in Joint Web Browser
  //   If this is not specify, default setting in MCU's configm.ini file will be used.
  var $jointBrowsingUrl;

  // Specify that all participants in the meeting will be in question mode AT ALL TIME.
  //  Note: the number of people in question mode is limited by the MCU license.
  //        Therefore, the number of people in meeting is also limited
  var $allQuestioner;
  
  // Is this meeting reserved?
  //   Each MCU has a limited number of connections.  Web application
  //   can control the number of reserved connections for the meeting.
  //   0=No(default), 1=Yes
  var $guaranteed;

  // CourseID
  // Only use to insert to DB
  // management recording file will use
  var $courseId;

  // ContinueRecordingId
  var $continueRecordingId;

  var $continueType;

  var $agenda;

  // only use in reservation meeting
  var $numofConnection;

  function JnjData() 
  {
          $this->reset();
  }


  //--------------------------------------------------------------------
  // DESC:    reset
  // PARAM:   Reset all the settings in user info
  //--------------------------------------------------------------------
  function reset() {
          $this->allQuestioner    = '0';
          $this->command          = '';
          $this->diskQuota        = '1000';  // 預設每個人1000MB(但沒測過超過1000MB會發生什麼事)
          $this->duration         = '';
          $this->guaranteed       = '0';   // 預設不限制連線人數(預約會議會用到可連線人數，此時此參數設成1，但我的程式好像沒把它設成1)
          $this->jointBrowsingUrl = '';
          $this->maxoutconnection = '200'; // 預設一個會議最多為200人(沒實際測過)
          $this->meetingId        = '';
          $this->meetingTitle     = '';
          $this->recording        = '';
          $this->ownerId          = '';
          $this->ownerEmail       = '';
          $this->ownerName        = '';
          $this->timestamp        = '';
          $this->courseId         = '';
          $this->continueRecordingId ='';
          $this->continueType = '';
          $this->agenda = '';
          $this->numofConnection = '';
  }

  // SetInstanceJnj:產生即時會議的jnj檔
  //
  // 參數 meetingTitle:會議標題(string)，allQuestioner:是否人人都是主持人(0:不是 1:是)[實際上沒用到]，jointBrowsingUrl:預設瀏覽的網址(string)，
  //      recording:是否產生紀錄檔 (0:不產生 1:產生)
  //
  // 回傳值:建立即時會議的jnj檔
  function SetInstanceJnj($meetingTitle, $allQuestioner, $jointBrowsingUrl, $recording, $continuType){

          $this->ownerName = mb_convert_encoding($this->ownerName,"UTF-8","big5");
          $this->meetingTitle = mb_convert_encoding($this->meetingTitle,"UTF-8","big5");
          $this->jointBrowsingUrl =mb_convert_encoding($this->jointBrowsingUrl,"UTF-8","big5");

          $this->diskQuota = GetDiskQuota($this->ownerId);
          if(empty($this->diskQuota))
                $this->diskQuota = 1000;
          else
                ;

          // 先將資料寫入資料庫，再將jnj檔產生
          $resultRow = InsertInstanceMeetingToDB($this);
          $this->meetingId = $resultRow['meetingId'] ;
          $this->timestamp = $resultRow['timestamp'] ;
          // 產生即時會議的jnj檔
          
          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="';
          $jnjformat = $jnjformat.$this->ownerId;
          $jnjformat = $jnjformat.'" diskquota="'.$this->diskQuota.'" maxoutconnection="'.$this->maxoutconnection.'"';
          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;
          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner>';
          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.$this->timestamp.'</timestamp>';
          $jnjformat = $jnjformat.'<meetingtitle>'.$this->meetingTitle.'</meetingtitle>';
          $jnjformat = $jnjformat.'<command recording="'.$this->recording.'" duration="0"';
          
          // 有給url的話加上 "default_joint_browsing_page="的設定
          if (!is_null($jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$this->jointBrowsingUrl.'"';
          else
              ;
          $jnjformat .= '>meeting<guaranteed>'.$this->guaranteed.'</guaranteed>';
          //  接續會議continueType為1，然後進行設定
          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              // continueRecordingId名字取的不好，這個變數的意思是指被接續的會議的meetingId
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          $jnjformat = $jnjformat.'</command></jnj>';
          return ($jnjformat); 
  }


  // SetInstanceJnj:產生加入會議的jnj檔
  //
  // 參數 studentName:學生姓名
  //
  // 回傳值:加入會議的jnj檔
  function SetJoinMeetingJnj($studentName) {

          $this->diskQuota = GetDiskQuota($this->ownerId);
          if(empty($this->diskQuota))
                $this->diskQuota = 1000;
          else
                ;
	  $studentName = mb_convert_encoding($studentName,"UTF-8","big5");

          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="'.$this->ownerId ;
          $jnjformat = $jnjformat.'" diskquota="'.$this->diskQuota.'" maxoutconnection="'.$this->maxoutconnection.'"';

          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;

          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';

          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';
          $jnjformat = $jnjformat.'<meetingtitle>'.$this->meetingTitle.'</meetingtitle>';  
          $jnjformat .= '<guest invited="1">'.$studentName.'</guest>';        

          $jnjformat = $jnjformat.'<command recording="'.$this->recording.'" duration="'.$this->duration.'"';


          if (!empty($this->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jnjData->jointBrowsingUrl.'"';
          else
              ;
          
          if ($this->numofConnection == 0) // 即時會議
                $jnjformat .= '>meeting<guaranteed>0</guaranteed>';
          else //預約會議
                $jnjformat .= '>meeting<guaranteed invited="0" uninvited="'.$this->numofConnection.'">0</guaranteed>';

          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              // continueRecordingId名字取的不好，這個變數的意思是指被接續的會議的meetingId
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          $jnjformat = $jnjformat.'</command></jnj>';
          
          return ($jnjformat);

  }


  // 有進入預約會議跟進入準備模式，因為兩個的jnj長的非常相像，
  // 所以加一個變數來去分別就好了，不另寫function
  function SetReservationJnj($prepara) {

          $this->ownerName = mb_convert_encoding($this->ownerName,"UTF-8","big5");
          
	  $this->diskQuota = GetDiskQuota($this->ownerId);
          if(empty($this->diskQuota))
                $this->diskQuota = 1000;
          else
                ;

          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="';
          $jnjformat = $jnjformat.$this->ownerId;
          $jnjformat = $jnjformat.'" diskquota="'.$this->diskQuota.'" maxoutconnection="'.$this->maxoutconnection.'"';
          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;
          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';
          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';
          $jnjformat = $jnjformat.'<meetingtitle>'.$this->meetingTitle.'</meetingtitle>';
          $jnjformat = $jnjformat.'<command recording="'.$this->recording.'" duration="'.$this->duration.'"';


          // prepare mode
          if($prepara) {
              $jnjformat = $jnjformat.' preparationmode="1"';
          }
          else
              ;

          if (!empty($jnjData->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jointBrowsingUrl.'"';
          else
              ;

          // 扣除自己已經進入會議
          $this->numofConnection = $this->numofConnection -1 ;
          $jnjformat .= '>meeting<guaranteed invited="0" uninvited="'.$this->numofConnection.'">0</guaranteed>';
          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              // 這裡的$this->continueRecordingId 為meeting Id 變數名稱取的不好
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          $jnjformat = $jnjformat.'</command></jnj>';
          return ($jnjformat);

  }

  // 設定playback mode的jnj檔內容
  function SetPlaybackMeetingJnj($studentName) {

	  $studentName = mb_convert_encoding($studentName,"UTF-8","big5");

          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="'.$this->ownerId.'"' ;

          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;

          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';

          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';
          $jnjformat .= '<guest invited="1">'.$studentName.'</guest>';

          $jnjformat = $jnjformat.'<command file="'.SearchingRecordingFileName($this->meetingId).'"';
          /*
          if (!empty($jnjData->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jnjData->jointBrowsingUrl.'"';
          else
              ;
           */
          $jnjformat .= '>playback<guaranteed>0</guaranteed>';
          /*
          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          */
          $jnjformat = $jnjformat.'</command></jnj>';

          return ($jnjformat);

  }

  // 下載錄影檔的JNJ內容
  function SetDownloadMeetingJnj($studentName) {

	  $studentName = mb_convert_encoding($studentName,"UTF-8","big5");

          // 所有資訊都從資料庫來 之後要改掉會先在之前寫到變數裡 暫時先寫死
          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="'.$this->ownerId.'"' ;

          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;

          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';

          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';
          $jnjformat .= '<guest invited="1">'.$studentName.'</guest>';

          $jnjformat = $jnjformat.'<command file="'.SearchingRecordingFileName($this->meetingId).'"';
          /*
          if (!empty($jnjData->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jnjData->jointBrowsingUrl.'"';
          else
              ;
           */
          $jnjformat .= '>download<guaranteed>0</guaranteed>';
          /*
          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          */
          $jnjformat = $jnjformat.'</command></jnj>';

          return ($jnjformat);

  }

  // 刪除錄影檔的JNJ內容
  // [jfish] 沒有用到下面這個function為什麼呢??
  function SetDeleteRecordingJnj($studentName) {

	  $studentName = mb_convert_encoding($studentName,"UTF-8","big5");

          // 所有資訊都從資料庫來 之後要改掉會先在之前寫到變數裡 暫時先寫死
          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="'.$this->ownerId.'"' ;

          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;

          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';

          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';

          $jnjformat = $jnjformat.'<command file="'.SearchingRecordingFileName($this->meetingId).'"';
          /*
          if (!empty($jnjData->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jnjData->jointBrowsingUrl.'"';
          else
              ;
           */
          $jnjformat .= '>delete<guaranteed>0</guaranteed>';
          /*
          if ($this->continueType != 0 ) {
              $jnjformat .='<continuemeeting userid="'.$this->ownerId;
              $jnjformat .='" file="'.SearchingRecordingFileName($this->continueRecordingId).'">'.$this->continueRecordingId.'</continuemeeting>';
          }
          else
              ;
          */
          $jnjformat = $jnjformat.'</command></jnj>';

          return ($jnjformat);

  }
  
  function SetLeaveMsgJnj($studentName) {

          $this->ownerName = mb_convert_encoding($this->ownerName,"UTF-8","big5");
          $this->meetingTitle = mb_convert_encoding($this->meetingTitle,"UTF-8","big5");
          $this->jointBrowsingUrl =mb_convert_encoding($this->jointBrowsingUrl,"UTF-8","big5");
          $studentName = mb_convert_encoding($studentName,"UTF-8","big5");

          $this->diskQuota = GetDiskQuota($this->ownerId);
          if(empty($this->diskQuota))
                $this->diskQuota = 1000;
          else
                ;

          InsertLevaeMsgToDB($this);
          // 所有資訊都從資料庫來 之後要改掉會先在之前寫到變數裡 暫時先寫死
          $jnjformat = '<?xml version="1.0" encoding="utf-8" ?><jnj>';
          $jnjformat = $jnjformat.'<owner id="'.$this->ownerId ;
          $jnjformat = $jnjformat.'" diskquota="'.$this->diskQuota.'" maxoutconnection="'.$this->maxoutconnection.'"';

          if (!empty($this->ownerEmail))
              $jnjformat = $jnjformat.' email="'.$this->ownerEmail.'"';  // 資料庫沒有eamil資訊的話的話email屬性不會加上去
          else
              ;

          $jnjformat = $jnjformat.'>'.$this->ownerName.'</owner'.'>';

          $jnjformat = $jnjformat.'<meetingid>'.$this->meetingId.'</meetingid>';
          $jnjformat = $jnjformat.'<timestamp>'.strtotime("now").'</timestamp>';
          $jnjformat = $jnjformat.'<meetingtitle>'.$this->meetingTitle.'</meetingtitle>';
          $jnjformat .= '<guest invited="1">'.$studentName.'</guest>';

          $jnjformat = $jnjformat.'<command recording="'.$this->recording.'" duration="'.$this->duration.'"';
          $jnjformat = $jnjformat.' max_message_duration="180"';


          /*
          if (!empty($jnjData->jointBrowsingUrl))
              $jnjformat .= ' default_joint_browsing_page="'.$jnjData->jointBrowsingUrl.'"';
          else
              ;
          */

          $jnjformat .= '>leavemessage<guaranteed>0</guaranteed>';
          $jnjformat = $jnjformat.'</command></jnj>';

          return ($jnjformat);
    }




}

  //--------------------------------------------------------------------------
  // NAME:    launchJoinnet
  // DESC:    Output HTTP response to make browser to launch JoinNet
  // PARAM:   $jnjContent [in]
  //              Content of JNJ file to be passed to the browser which in
  //              turn will pass to JoinNet
  //--------------------------------------------------------------------------
  function hitLaunchJoinnet($jnjContent){
      $randomFileName = uniqid("launch");
      header("Content-Disposition: inline; filename=$randomFileName.jnj");
      header("Content-Type: application/jnj");
      header("Content-Length: ".(strlen($jnjContent)+3));
      header("Cache-Control: private");
      header("Pragma: private");
      print $jnjContent;
      flush();
      exit() ;
  }

  function StartJoinnet($jnjformat, $type = "other"){
      global $course_id;
      $mmc_jnj_config = new MMC_Jnj_Config();
      $mcu_config = new MCU_Config();
      $mmc_path_config = new MMC_Path_Config();
      $encryptor = new EncryptionTool();
     
      $stuId = db_getAid();
      $courseId = $course_id;
      $courseName = db_getCourseName(null, 1);

      if($type == "student")
        InsertMyStudentMeetingLog($courseId, $courseName, $stuId);
 
      $errcode =$encryptor->pkeEncrypt($ans,$jnjformat,$mmc_jnj_config->privateKeyPath,$mmc_jnj_config->publicKeyPath,$mmc_jnj_config->siteId,$mmc_jnj_config->passPhrase);
      if($errcode != 0) {
          // error jnjEncrpty
          echo "error!!!";
          die ;
      }
      else
          ;
     
      $jnjFile=""; 
      // [jfish]要去看UPSmmc的jnjFile設定
      $jnjFile = "# if you see this file, please download and reinstall JoinNet software from http://www.homemeeting.com\r\n[general]\r\ncodetype={$mcu_config->codeType}\r\nip={$mcu_config->Mcu_ip}\r\ndomain=HomeMeeting\r\nportm={$mcu_config->portm}\r\nportm2=\r\ngui_rec_ver=\r\ngui_min_ver=\r\nskin2=http://{$mcu_config->Mcu_ip}/Skin/Skin2_cybercc";
      $jnjFile .= "\r\nuserinfo={$ans}";
      // 確認完成之後才可以開  不然會死得很難看

        echo"<p>使用說明：我們的網路會議需要安裝 JoinNet 軟體來使用，JoinNet 為安裝於使用者端之免費軟體。<br>
        在您安裝 JoinNet 軟體之後，您也可以利用執行測試精靈來確定您的電腦是否符合系統需求。</p>
        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">
        <tbody><tr>
        <td nowrap=\"true\">
        <p>
        <a href=\"http://www.webmeeting.com.tw/download_joinnet.php\" target=\"_blank\"><img src=\"{$mmc_path_config->mcu_path}images/icon_download.gif\" align=\"absmiddle\" border=\"0\" vspace=\"1\" hspace=\"5\">下載 JoinNet</a>

        </p>
        </td>
        </tr>
        <tr>
        <td nowrap=\"true\">
        <p>
        <a href=\"{$mmc_path_config->mcu_path}joinnet_wizard.php\"><img src=\"{$mmc_path_config->mcu_path}images/icon_test_wizard.gif\" align=\"absmiddle\" border=\"0\" vspace=\"1\" hspace=\"5\">執行測試精靈                     </a>
        </p>

        </td>
        </tr>
        </tbody></table>";
      $_SESSION['jnjFile'] = $jnjFile;
      echo "<meta http-equiv='refresh' content='0;url=startJoinnet.php'>";

  }


?>

