<HTML>
<HEAD>
<TITLE>語音聊天室</TITLE>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
</HEAD>
<CENTER>
<OBJECT
	  classid="clsid:873F99F8-511C-4E06-8BB8-4D9E09AC2923"
	  codebase="http://IP/learn/voice/client/clientProj1.inf"
	  width=732
	  height=507
	  align=center
	  hspace=0
	  vspace=0
>
</OBJECT>
</CENTER>
</BODY>
</HTML>